# Generated by Django 6.0 on 2026-01-21 21:09

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('PAS', 'Pasaporte'), ('CED', 'Cedula')], max_length=3)),
                ('nro_documento', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(default=usuarios.models.generar_code, max_length=16, unique=True)),
            ],
        ),
    ]
